import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { DOCUMENT_FOLDERS } from '../config/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../../');

export const ACA_DISCLAIMER = `\n---\n\n> **⚠️ LEGAL DISCLAIMER — PLEASE READ**\n>\n> This document was generated by **LexForge™**, an automated legal document generation service operated by Archer Chain Analytics (ISC: 102237785). It is provided as a **draft template only** and does **not** constitute legal advice.\n>\n> This document has not been reviewed by a licensed legal professional. Laws and regulations vary by jurisdiction and change over time. Before signing or relying on this document, you should obtain independent legal advice from a qualified lawyer licensed in the applicable jurisdiction.\n>\n> Archer Chain Analytics expressly disclaims all liability arising from the use of this document without independent legal review.\n>\n> *Sovereignty // Integrity // Inexorabilis*\n`;

export function resolveTemplatePath(documentCode, jurisdiction, language) {
  const folder = DOCUMENT_FOLDERS[documentCode];
  if (!folder) throw new Error(`Unknown document code: ${documentCode}`);
  return join(ROOT, 'templates', folder, jurisdiction, `${language}.md`);
}

export function mergeVariables(template, variables) {
  return template.replace(/\{\{([^}|]+)(?:\|([^}]*))?\}\}/g, (_, key, def) => {
    const val = variables[key.trim()];
    if (val !== undefined && val !== null && val !== '') return val;
    if (def !== undefined) return def;
    return `{{${key.trim()}}}`;
  });
}

export function renderTemplate(documentCode, jurisdiction, language, variables) {
  const templatePath = resolveTemplatePath(documentCode, jurisdiction, language);
  let content;
  try {
    content = readFileSync(templatePath, 'utf8');
  } catch {
    throw new Error(`Template not found: ${templatePath}`);
  }
  const merged = mergeVariables(content, variables);
  return merged.includes('⚠️ LEGAL DISCLAIMER') ? merged : merged + ACA_DISCLAIMER;
}
