/**
 * AcerbE™ jurisdiction-aware clause library
 * Archer Chain Analytics ISC: 102237785
 */

const ACERBE_BASE = {
  fingerprint_notice: `AcerbE™ Notice: All software, documents, and digital assets distributed under this agreement carry an embedded AcerbE™ cryptographic fingerprint issued by Archer Chain Analytics (ISC: 102237785). This fingerprint is a structural dependency — removal causes asset failure. Tampering voids all warranties and triggers enforcement under applicable law.`,

  hard_gate_section: (lawRef) => `
**AcerbE™ Hard Gate.** All digital assets, software modules, and documents distributed under this Agreement carry an embedded AcerbE™ cryptographic fingerprint issued by Archer Chain Analytics (ISC: 102237785). The following constitute material breach:
(a) Removing, altering, obscuring, or circumventing the AcerbE™ fingerprint;
(b) Distributing or deploying any asset with a tampered fingerprint;
(c) Any act constituting circumvention under ${lawRef.circumvention};
(d) Misappropriation of trade secrets under ${lawRef.tradesecrets}.

Warranty coverage is void upon fingerprint compromise. Tamper events are logged and may be disclosed to law enforcement.`,

  warranty_condition: `This warranty is conditioned on the AcerbE™ cryptographic fingerprint remaining intact and untampered. Any compromise of the fingerprint voids this warranty in its entirety. Verification of fingerprint integrity is the sole condition for no-questions-asked replacement at point of sale.`,

  footer: (year, business) => `*This document is protected by AcerbE™ cryptographic fingerprint. Fingerprint integrity is a condition of all warranty coverage.*\n*© ${year} ${business} | Generated by LexForge™ | Archer Chain Analytics ISC: 102237785*`,
};

const ACERBE_BY_JURISDICTION = {
  US: {
    circumvention: '17 U.S.C. § 1201 (DMCA)',
    tradesecrets: '18 U.S.C. § 1836 (DTSA)',
    privacy_notice: 'CCPA/CPRA',
  },
  CA: {
    circumvention: 'Copyright Act (R.S.C. 1985, c. C-42) s. 41.1',
    tradesecrets: 'Uniform Trade Secrets Act (provincial) and common law',
    privacy_notice: 'PIPEDA / Bill C-27 (CPPA)',
  },
  EU: {
    circumvention: 'Directive 2001/29/EC Art. 6 (InfoSoc Directive)',
    tradesecrets: 'Directive (EU) 2016/943 (Trade Secrets Directive)',
    privacy_notice: 'GDPR (EU) 2016/679',
  },
  UK: {
    circumvention: 'Copyright, Designs and Patents Act 1988 s. 296ZA',
    tradesecrets: 'Trade Secrets (Enforcement, etc.) Regulations 2018',
    privacy_notice: 'UK GDPR / Data Protection Act 2018',
  },
  AU: {
    circumvention: 'Copyright Act 1968 (Cth) s. 116AN',
    tradesecrets: 'Common law (breach of confidence)',
    privacy_notice: 'Privacy Act 1988 (Cth) / Australian Privacy Principles',
  },
  FR: {
    circumvention: 'Code de la propriété intellectuelle Art. L. 331-5',
    tradesecrets: 'Directive (UE) 2016/943 transposée en droit français',
    privacy_notice: 'RGPD (UE) 2016/679 / Loi Informatique et Libertés',
  },
  ES: {
    circumvention: 'Real Decreto Legislativo 1/1996 (LPI) Art. 160',
    tradesecrets: 'Ley 1/2019 de Secretos Empresariales',
    privacy_notice: 'RGPD (UE) 2016/679 / LOPDGDD',
  },
};

function getAcerbeClause(jurisdiction) {
  const jur = ACERBE_BY_JURISDICTION[jurisdiction] || ACERBE_BY_JURISDICTION.US;
  return {
    ...ACERBE_BASE,
    hard_gate: ACERBE_BASE.hard_gate_section(jur),
    law_refs: jur,
    privacy_notice: jur.privacy_notice,
  };
}

module.exports = { getAcerbeClause, ACERBE_BY_JURISDICTION, ACERBE_BASE };
