#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { getAcerbeClause } = require('./acerbe_clauses.cjs');
const { JURISDICTION_RULES, JURISDICTION_LANGUAGES, ALL_JURISDICTIONS } = require('./jurisdiction_rules.cjs');

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const SKIP_EXISTING = args.includes('--skip-existing');
const jurIdx = args.indexOf('--jurisdiction');
const jurFilter = jurIdx !== -1 ? args[jurIdx + 1].split(',') : null;
const jurisdictionsToRun = jurFilter || ALL_JURISDICTIONS;

const REPO_ROOT = path.resolve(__dirname, '..');
const TEMPLATES_DIR = path.join(REPO_ROOT, 'templates');

const DOCS = [
  { id: '01-NDA', name: 'Non-Disclosure Agreement' },
  { id: '02-SLA', name: 'Service Level Agreement' },
  { id: '03-MSA', name: 'Master Services Agreement' },
  { id: '04-ICA', name: 'Independent Contractor Agreement' },
  { id: '05-EUA', name: 'End User License Agreement' },
  { id: '06-TOS', name: 'Terms of Service' },
  { id: '07-PP',  name: 'Privacy Policy' },
  { id: '08-RPA', name: 'Revenue Participation Agreement' },
  { id: '09-LOI', name: 'Letter of Intent' },
  { id: '10-MOU', name: 'Memorandum of Understanding' },
  { id: '11-IP',  name: 'IP Assignment Agreement' },
  { id: '12-ESA', name: 'Employment Services Agreement' },
  { id: '13-PSA', name: 'Professional Services Agreement' },
  { id: '14-DPA', name: 'Data Processing Agreement' },
  { id: '15-WA',  name: 'Warranty Agreement' },
  { id: '16-LIC', name: 'Software License Agreement' },
  { id: '17-PAR', name: 'Partnership Agreement' },
  { id: '18-CES', name: 'Consulting Agreement' },
  { id: '19-INV', name: 'Investment Agreement' },
];

function buildFrontmatter(doc, jur, lang, rules) {
  return `<!--
  LexForge™ | ARC-LXF-001
  Document : ${doc.name}
  Jurisdiction: ${jur} | Language: ${lang}
  Governing Law: ${rules.governing_law}
  Currency: ${rules.currency}
  Generated: ${new Date().toISOString().split('T')[0]}
  Owner: Neil Scott Archer | Archer Chain Analytics | ISC 102237785
  AcerbE™ Hard Gate: ACTIVE
-->`;
}

function buildHeader(doc, jur, lang, rules) {
  return `# ${doc.name}
**LexForge™ Document ID:** ARC-LXF-${doc.id} | **Jurisdiction:** ${jur} | **Language:** ${lang}
**Governing Law:** ${rules.governing_law} | **Currency:** ${rules.currency}
**Effective Date:** {{EFFECTIVE_DATE}}

---`;
}

function buildFooter(doc, jur, rules, acerbe) {
  return `
---

## ACERBE™ FINGERPRINT NOTICE

This document and all associated digital deliverables carry an embedded AcerbE™ cryptographic fingerprint.

- Removal or tampering **immediately voids** this agreement and all warranties
- Tampering may violate ${acerbe.circumvention} and ${acerbe.tradesecrets}
- Forensic trace is preserved regardless of file modification

> *AcerbE™ is a registered product of Archer Chain Analytics | ISC 102237785*

---

*Generated by LexForge™ | ARC-LXF-001 | © 2026 Neil Scott Archer / Archer Chain Analytics | ISC: 102237785*
*Sovereignty // Integrity // Inexorabilis*
*This template requires review by qualified legal counsel before use. Not legal advice.*`;
}

function writeTemplate(doc, jur, lang, content) {
  const outPath = path.join(TEMPLATES_DIR, doc.id, jur, `${lang}.md`);
  if (SKIP_EXISTING && fs.existsSync(outPath)) {
    console.log(`[SKIP] ${outPath}`);
    return;
  }
  if (DRY_RUN) {
    console.log(`[DRY] ${outPath}`);
    return;
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`[WRITE] ${outPath}`);
}

function buildNDA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Disclosing Party:** {{DISCLOSING_PARTY_LEGAL_NAME}} | **Receiving Party:** {{RECEIVING_PARTY_LEGAL_NAME}}

---

## 1. CONFIDENTIAL INFORMATION
Includes all non-public technical, financial, business, and operational information disclosed by Disclosing Party, including AcerbE™ fingerprint architecture and cryptographic schema.

## 2. OBLIGATIONS
Receiving Party shall: (a) hold in strict confidence; (b) use only for {{PURPOSE}}; (c) not disclose to third parties without prior written consent.

## 3. TERM
{{NDA_TERM|3 years}} from Effective Date. Trade secrets protected indefinitely.

## 4. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

## SIGNATURES
**DISCLOSING PARTY:** Sig: ___ | Name: {{DISCLOSING_SIGNATORY}} | Date: ___
**RECEIVING PARTY:** Sig: ___ | Name: {{RECEIVING_SIGNATORY}} | Date: ___`;
}

function buildSLA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Provider:** {{PROVIDER_LEGAL_NAME}} | **Customer:** {{CUSTOMER_LEGAL_NAME}}

---

## 1. SERVICE LEVELS
Provider shall maintain {{UPTIME_TARGET|99.9%}} uptime measured monthly, excluding scheduled maintenance.

## 2. INCIDENT RESPONSE
- P1 (Critical): {{P1_RESPONSE|1 hour}} response / {{P1_RESOLUTION|4 hours}} resolution
- P2 (High): {{P2_RESPONSE|4 hours}} response / {{P2_RESOLUTION|24 hours}} resolution
- P3 (Medium): {{P3_RESPONSE|1 business day}} response

## 3. CREDITS
Service credits of {{CREDIT_RATE|10%}} of monthly fees per {{CREDIT_THRESHOLD|0.1%}} downtime below SLA target.

## 4. ACERBE™
AcerbE™ fingerprint integrity is a prerequisite for all warranty and credit claims under this SLA.

## 5. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.`;
}

function buildMSA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Provider:** {{PROVIDER_LEGAL_NAME}} ("Provider") | **Customer:** {{CUSTOMER_LEGAL_NAME}} ("Customer")
**Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. SCOPE
Provider shall perform services described in each Statement of Work ("SOW") incorporated into this Agreement. Each SOW is incorporated herein.

## 2. FEES AND PAYMENT
Fees per SOW, denominated in ${rules.currency}. Payment due {{PAYMENT_TERMS|30 days}}. Late interest: {{LATE_RATE|1.5%}}/month.

## 3. INTELLECTUAL PROPERTY
Provider retains all pre-existing IP. Work product ownership per SOW. AcerbE™ fingerprinted deliverables subject to hard gate: tampering violates ${acerbe.circumvention}.

## 4. CONFIDENTIALITY
Mutual NDA. Each Party protects the other's Confidential Information. Survives 3 years post-termination; trade secrets indefinitely.

## 5. TERM AND TERMINATION
Continues until all SOWs complete or terminated for cause (30-day cure). Convenience termination: 30 days' notice + payment for work completed.

## 6. GOVERNING LAW
${rules.governing_law}. Arbitration: ${rules.arbitration_body} under ${rules.arbitration_rules}.

## SIGNATURES
**PROVIDER:** Sig: ___ | Name: {{PROVIDER_SIGNATORY}} | Title: {{PROVIDER_TITLE}} | Date: ___
**CUSTOMER:** Sig: ___ | Name: {{CUSTOMER_SIGNATORY}} | Title: {{CUSTOMER_TITLE}} | Date: ___`;
}

function buildICA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Client:** {{CLIENT_LEGAL_NAME}} ("Client") | **Contractor:** {{CONTRACTOR_LEGAL_NAME}} ("Contractor")
**Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. INDEPENDENT CONTRACTOR STATUS
Contractor is an independent contractor. No employment, partnership, or agency relationship is created. Contractor is responsible for own taxes (${rules.tax_form} issued where applicable).

## 2. SERVICES
Contractor shall perform services per each Statement of Work. Services performed in a professional manner.

## 3. COMPENSATION
Fees per SOW in ${rules.currency}. Payment due {{PAYMENT_TERMS|30 days}}. No benefits, workers' compensation, or employer contributions.

## 4. INTELLECTUAL PROPERTY
Work product owned by Client upon full payment. Contractor retains tools and methodologies. AcerbE™ hard gate applies to all digital deliverables: tampering violates ${acerbe.circumvention} and ${acerbe.tradesecrets}.

## 5. CONFIDENTIALITY
Contractor holds Client's Confidential Information in strict confidence. Survives 3 years.

## 6. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body} under ${rules.arbitration_rules}.

## SIGNATURES
**CLIENT:** Sig: ___ | Name: {{CLIENT_SIGNATORY}} | Date: ___
**CONTRACTOR:** Sig: ___ | Name: {{CONTRACTOR_SIGNATORY}} | Date: ___`;
}

function buildEUA(jur, lang, rules, acerbe) {
  return `**Product:** {{PRODUCT_NAME}} | **Version:** {{VERSION}} | **Effective Date:** {{EFFECTIVE_DATE}}

---

## LICENSE GRANT
You are granted a limited, non-exclusive, non-transferable license to use {{PRODUCT_NAME}} for personal or internal business use, subject to this EULA.

## RESTRICTIONS
You may NOT: (a) copy, modify, or create derivative works; (b) reverse engineer or decompile; (c) redistribute, sublicense, or resell; (d) remove or tamper with AcerbE™ fingerprints; (e) use for unlawful purposes.

## ACERBE™ FINGERPRINT
This product carries an embedded AcerbE™ cryptographic fingerprint. Removal or tampering: (a) terminates this license immediately; (b) voids all warranties; (c) may violate ${acerbe.circumvention} and ${acerbe.tradesecrets}.

## WARRANTY
Product warrants material conformance to documentation for {{WARRANTY_PERIOD|90 days}} provided AcerbE™ fingerprint is intact. Implied warranties disclaimed to fullest extent permitted by ${rules.governing_law} law.

## GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

BY INSTALLING OR USING THIS PRODUCT, YOU ACCEPT THIS EULA.`;
}

function buildTOS(jur, lang, rules, acerbe) {
  return `**Service:** {{SERVICE_NAME}} | **Operator:** {{OPERATOR_LEGAL_NAME}} | **Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. ACCEPTANCE
By accessing or using the Service, you agree to these Terms. If you do not agree, do not use the Service.

## 2. ELIGIBILITY
You must be at least 18 years of age and capable of forming a binding contract under ${rules.governing_law} law.

## 3. ACCOUNT
You are responsible for maintaining the security of your account credentials. Notify us immediately of unauthorized access.

## 4. ACCEPTABLE USE
You shall not: (a) violate applicable law; (b) infringe third-party rights; (c) tamper with AcerbE™ fingerprints embedded in Service assets; (d) attempt to reverse engineer the Service; (e) use the Service for spam or malicious activity.

## 5. INTELLECTUAL PROPERTY
All Service content is owned by Operator or its licensors. AcerbE™ fingerprinted assets are protected under ${acerbe.circumvention} and ${acerbe.tradesecrets}. No license is granted beyond what is expressly stated.

## 6. PRIVACY
Your use of the Service is subject to our Privacy Policy, which complies with ${rules.privacy_law}.

## 7. DISCLAIMERS
SERVICE PROVIDED "AS IS." OPERATOR DISCLAIMS ALL IMPLIED WARRANTIES TO THE FULLEST EXTENT PERMITTED BY ${rules.governing_law.toUpperCase()} LAW.

## 8. LIMITATION OF LIABILITY
OPERATOR'S LIABILITY IS LIMITED TO THE GREATER OF FEES PAID IN THE PRIOR 12 MONTHS OR $100 ${rules.currency}.

## 9. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body} under ${rules.arbitration_rules}.

## 10. CHANGES
We may update these Terms with notice. Continued use constitutes acceptance.`;
}

function buildPP(jur, lang, rules, acerbe) {
  return `**Operator:** {{OPERATOR_LEGAL_NAME}} | **Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. INTRODUCTION
This Privacy Policy describes how we collect, use, and protect personal information in compliance with ${rules.privacy_law}.

**AcerbE™ Notice:** Our platform employs AcerbE™ digital fingerprinting on all software and digital assets. Fingerprint verification events may be logged as described herein.

## 2. INFORMATION WE COLLECT
- Account data (name, email, password)
- Usage data (IP address, browser, device)
- AcerbE™ fingerprint verification events
- Payment information (processed by {{PAYMENT_PROCESSOR}})
- Blockchain wallet addresses (if applicable)

## 3. HOW WE USE INFORMATION
- Provide and operate the Service
- Process transactions
- Verify AcerbE™ fingerprint integrity
- Comply with ${rules.privacy_law}
- Enforce our Terms of Service

## 4. DATA TRANSFERS
Data may be transferred ${rules.data_transfer}.

## 5. DATA BREACH NOTIFICATION
We will notify you of a data breach affecting your personal information within ${rules.breach_notice}.

## 6. YOUR RIGHTS
You have rights under ${rules.privacy_law} including access, correction, deletion, and portability. Contact: {{PRIVACY_CONTACT_EMAIL}}

## 7. CONTACT
**Privacy Officer:** {{PRIVACY_OFFICER_NAME}} | **Email:** {{PRIVACY_CONTACT_EMAIL}}`;
}

function buildRPA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Company:** {{COMPANY_LEGAL_NAME}} ("Company") | **Participant:** {{PARTICIPANT_LEGAL_NAME}} ("Participant")
**Agreement Date:** {{AGREEMENT_DATE}}

---

## 1. PARTICIPATION
Company grants Participant a {{PARTICIPATION_RATE}}% participation in Net Revenue from {{REVENUE_SOURCES}}, in exchange for {{CONTRIBUTION_DESCRIPTION}}.

## 2. PAYMENTS
Payments due within {{PAYMENT_DUE_DAYS|30}} days after each {{PAYMENT_PERIOD|calendar month}}. Currency: ${rules.currency}. Late interest: {{LATE_RATE|1.5%}}/month.

## 3. REPORTING
Monthly revenue reports within {{REPORT_DAYS|15}} days of period end. Audit rights annually on {{AUDIT_NOTICE|30}} days' notice.

## 4. ACERBE™
AcerbE™ fingerprinted assets central to revenue stream. Tampering constitutes material breach. Enforcement under ${acerbe.circumvention}.

## 5. TERM
{{INITIAL_TERM|3 years}}. Termination for cause: 30-day cure period.

## 6. GOVERNING LAW
${rules.governing_law}. Arbitration: ${rules.arbitration_body}.

## SIGNATURES
**COMPANY:** Sig: ___ | Name: {{COMPANY_SIGNATORY}} | Date: ___
**PARTICIPANT:** Sig: ___ | Name: {{PARTICIPANT_SIGNATORY}} | Date: ___`;
}

function buildLOI(jur, lang, rules, acerbe) {
  return `**Date:** {{LOI_DATE}} | **Re:** Letter of Intent — {{TRANSACTION_DESCRIPTION}}

---

This LOI is submitted by {{INITIATING_PARTY}} ("Initiating Party") to {{RECEIVING_PARTY}} ("Receiving Party").

## BINDING PROVISIONS
The following are binding upon execution:
1. Confidentiality obligations (mutual, 2 years)
2. Exclusivity period: {{EXCLUSIVITY_PERIOD|60 days}}
3. AcerbE™ fingerprint acknowledgment — all shared digital assets carry AcerbE™ and tampering constitutes material breach

## NON-BINDING PROVISIONS
The following are non-binding expressions of intent:
- Transaction structure: {{TRANSACTION_STRUCTURE}}
- Proposed consideration: {{CONSIDERATION}}
- Target closing date: {{TARGET_CLOSE}}

## GOVERNING LAW
${rules.governing_law}.

**INITIATING PARTY:** Sig: ___ | Name: {{INITIATING_SIGNATORY}} | Date: ___
**RECEIVING PARTY:** Sig: ___ | Name: {{RECEIVING_SIGNATORY}} | Date: ___`;
}

function buildMOU(jur, lang, rules, acerbe) {
  return `## PARTIES
**Party A:** {{PARTY_A_LEGAL_NAME}} | **Party B:** {{PARTY_B_LEGAL_NAME}}
**Date:** {{MOU_DATE}}

---

## PURPOSE
The Parties intend to {{PURPOSE_DESCRIPTION}}.

## NON-BINDING INTENT
Except for Sections marked BINDING, this MOU is non-binding and does not create legal obligations.

## BINDING PROVISIONS
- Confidentiality: Each Party protects the other's Confidential Information for {{CONF_TERM|2 years}}
- No Partnership: Nothing herein creates a partnership, joint venture, or agency
- AcerbE™: All shared digital assets carry AcerbE™ fingerprint. Tampering violates ${acerbe.circumvention}

## GOVERNING LAW
${rules.governing_law}.

**PARTY A:** Sig: ___ | Name: {{PARTY_A_SIGNATORY}} | Date: ___
**PARTY B:** Sig: ___ | Name: {{PARTY_B_SIGNATORY}} | Date: ___`;
}

function buildIP(jur, lang, rules, acerbe) {
  return `## PARTIES
**Assignor:** {{ASSIGNOR_LEGAL_NAME}} | **Assignee:** {{ASSIGNEE_LEGAL_NAME}}

---

## 1. ASSIGNMENT
Assignor irrevocably assigns to Assignee all right, title, and interest in: {{IP_DESCRIPTION}}, including all patents, copyrights, trade secrets, and related rights worldwide.

## 2. CONSIDERATION
${rules.currency} {{CONSIDERATION_AMOUNT}} paid in full, receipt acknowledged.

## 3. WORK FOR HIRE
To the extent permitted by ${rules.governing_law} law, all Work Product constitutes a work made for hire.

## 4. MORAL RIGHTS WAIVER
Assignor waives all moral rights to the fullest extent permitted by applicable law.

## 5. ACERBE™
All digital deliverables carry AcerbE™ fingerprint. Assignment is void if fingerprint is tampered with prior to delivery. Enforcement: ${acerbe.circumvention}.

## 6. FURTHER ASSURANCES
Assignor shall execute additional documents as needed to perfect Assignee's ownership.

## 7. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

**ASSIGNOR:** Sig: ___ | Name: {{ASSIGNOR_SIGNATORY}} | Date: ___
**ASSIGNEE:** Sig: ___ | Name: {{ASSIGNEE_SIGNATORY}} | Date: ___`;
}

function buildESA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Employer:** {{EMPLOYER_LEGAL_NAME}} | **Employee:** {{EMPLOYEE_LEGAL_NAME}}
**Start Date:** {{START_DATE}}

---

## 1. POSITION AND DUTIES
Employee is hired as {{JOB_TITLE}}. Duties per Schedule A.

## 2. COMPENSATION
Base salary: ${rules.currency} {{BASE_SALARY}} per {{PAY_PERIOD|year}}. Benefits: {{BENEFITS_DESCRIPTION}}.

## 3. AT-WILL EMPLOYMENT
Employment is at-will and may be terminated by either party at any time with {{NOTICE_PERIOD|2 weeks}} notice, subject to ${rules.governing_law} law.

## 4. INTELLECTUAL PROPERTY
All work product created during employment is owned by Employer. Employee assigns all IP rights herein.

## 5. CONFIDENTIALITY
Employee shall not disclose Employer's Confidential Information during or after employment. Survives {{CONF_SURVIVAL|3 years}}.

## 6. ACERBE™
Unauthorized removal or tampering with AcerbE™ fingerprints on Employer's digital assets constitutes immediate grounds for termination for cause and may violate ${acerbe.circumvention}.

## 7. GOVERNING LAW
${rules.governing_law}.

**EMPLOYER:** Sig: ___ | Name: {{EMPLOYER_SIGNATORY}} | Date: ___
**EMPLOYEE:** Sig: ___ | Name: {{EMPLOYEE_SIGNATORY}} | Date: ___`;
}

function buildPSA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Client:** {{CLIENT_LEGAL_NAME}} | **Provider:** {{PROVIDER_LEGAL_NAME}}

---

## 1. SERVICES
Provider shall deliver services per each SOW attached hereto.

## 2. FEES
${rules.currency} per SOW. Net {{PAYMENT_TERMS|30}} days. Late fee: {{LATE_RATE|1.5%}}/month.

## 3. WORK PRODUCT
Upon full payment, Client owns all deliverables. Provider retains general skills and methodologies.

## 4. WARRANTIES
Provider warrants services will be performed in a professional manner conforming to industry standards.

## 5. ACERBE™
All digital deliverables carry AcerbE™ cryptographic fingerprint. Tampering voids warranties and may violate ${acerbe.circumvention}.

## 6. LIMITATION OF LIABILITY
Provider's liability capped at fees paid in prior 3 months.

## 7. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

**CLIENT:** Sig: ___ | Name: {{CLIENT_SIGNATORY}} | Date: ___
**PROVIDER:** Sig: ___ | Name: {{PROVIDER_SIGNATORY}} | Date: ___`;
}

function buildDPA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Controller:** {{CONTROLLER_LEGAL_NAME}} | **Processor:** {{PROCESSOR_LEGAL_NAME}}

---

## 1. SCOPE
Processor processes personal data on behalf of Controller as described in Annex 1.

## 2. PROCESSOR OBLIGATIONS
Processor shall: (a) process data only on Controller's documented instructions; (b) implement appropriate technical and organizational security measures; (c) not engage sub-processors without prior written consent; (d) assist Controller in fulfilling data subject rights under ${rules.privacy_law}.

## 3. SUB-PROCESSORS
Approved sub-processors listed in Annex 2. Processor provides 30 days' notice of changes.

## 4. DATA BREACH
Processor notifies Controller within ${rules.breach_notice} of becoming aware of a personal data breach.

## 5. ACERBE™
AcerbE™ fingerprint tampering on any processed digital asset constitutes a security event requiring immediate notification under this DPA. Enforcement: ${acerbe.circumvention}.

## 6. GOVERNING LAW
${rules.governing_law}. This DPA is governed by ${rules.privacy_law}.

**CONTROLLER:** Sig: ___ | Name: {{CONTROLLER_SIGNATORY}} | Date: ___
**PROCESSOR:** Sig: ___ | Name: {{PROCESSOR_SIGNATORY}} | Date: ___`;
}

function buildWA(jur, lang, rules, acerbe) {
  return `## PARTIES
**Warrantor:** {{WARRANTOR_LEGAL_NAME}} | **Beneficiary:** {{BENEFICIARY_LEGAL_NAME}}
**Product/Service:** {{PRODUCT_SERVICE_NAME}}

---

## 1. WARRANTY
Warrantor warrants that {{PRODUCT_SERVICE_NAME}} will conform materially to its documentation for {{WARRANTY_PERIOD|90 days}} from date of delivery.

## 2. NO-QUESTIONS-ASKED REPLACEMENT
Any defect, breakage, or non-conformance: return to point of sale for immediate replacement. No questions asked. This warranty is valid only while the AcerbE™ fingerprint remains intact with zero tampering marks.

## 3. ACERBE™ CONDITION
This warranty is void if the AcerbE™ cryptographic fingerprint has been removed, altered, or shows any tampering markers. Tampering may additionally violate ${acerbe.circumvention}.

## 4. EXCLUSIONS
Warranty does not cover: (a) misuse or unauthorized modification; (b) AcerbE™ fingerprint tampering; (c) damage from causes outside Warrantor's control.

## 5. GOVERNING LAW
${rules.governing_law}.`;
}

function buildLIC(jur, lang, rules, acerbe) {
  return `## PARTIES
**Licensor:** {{LICENSOR_LEGAL_NAME}} | **Licensee:** {{LICENSEE_LEGAL_NAME}}
**Product:** {{PRODUCT_NAME}} v{{VERSION}}

---

## 1. GRANT
Licensor grants Licensee a {{LICENSE_TYPE|non-exclusive, non-transferable}} license to use {{PRODUCT_NAME}} for {{USE_CASE|internal business purposes}}.

## 2. RESTRICTIONS
Licensee shall not: (a) sublicense, sell, or distribute; (b) reverse engineer or decompile; (c) remove or tamper with AcerbE™ fingerprints; (d) use beyond licensed scope.

## 3. ACERBE™ STRUCTURAL DEPENDENCY
AcerbE™ fingerprint is a structural component of this software. Removal causes functional collapse. Tampering: (a) auto-terminates this license; (b) voids all warranties; (c) may violate ${acerbe.circumvention} and ${acerbe.tradesecrets}.

## 4. TERM
{{LICENSE_TERM|perpetual}} unless terminated. Auto-terminates on AcerbE™ tampering or material breach.

## 5. FEES
${rules.currency} {{LICENSE_FEE}} per {{LICENSE_PERIOD|year}}.

## 6. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

**LICENSOR:** Sig: ___ | Name: {{LICENSOR_SIGNATORY}} | Date: ___
**LICENSEE:** Sig: ___ | Name: {{LICENSEE_SIGNATORY}} | Date: ___`;
}

function buildPAR(jur, lang, rules, acerbe) {
  return `## PARTIES
**Partner A:** {{PARTNER_A_LEGAL_NAME}} | **Partner B:** {{PARTNER_B_LEGAL_NAME}}
**Formation Date:** {{FORMATION_DATE}}

---

## 1. FORMATION
The Parties form a general partnership under ${rules.governing_law} law for the purpose of {{PARTNERSHIP_PURPOSE}}.

## 2. CONTRIBUTIONS
- Partner A: {{PARTNER_A_CONTRIBUTION}}
- Partner B: {{PARTNER_B_CONTRIBUTION}}

## 3. PROFIT SHARING
- Partner A: {{PARTNER_A_SHARE}}% | Partner B: {{PARTNER_B_SHARE}}%

## 4. MANAGEMENT
Decisions require {{DECISION_THRESHOLD|majority}} approval. Day-to-day management: {{MANAGING_PARTNER}}.

## 5. RIGHT OF FIRST REFUSAL
Before transferring any partnership interest, offering Partner must first offer to remaining Partners at same price and terms. ROFR period: {{ROFR_PERIOD|30 days}}.

## 6. ACERBE™
Tampering with AcerbE™ fingerprints on partnership digital assets constitutes material breach and triggers immediate buyout at book value. Enforcement: ${acerbe.circumvention}.

## 7. GOVERNING LAW
${rules.governing_law}. Arbitration: ${rules.arbitration_body}.

**PARTNER A:** Sig: ___ | Name: {{PARTNER_A_SIGNATORY}} | Date: ___
**PARTNER B:** Sig: ___ | Name: {{PARTNER_B_SIGNATORY}} | Date: ___`;
}

function buildCES(jur, lang, rules, acerbe) {
  return `## PARTIES
**Client:** {{CLIENT_LEGAL_NAME}} | **Consultant:** {{CONSULTANT_LEGAL_NAME}}
**Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. INDEPENDENT CONTRACTOR
Consultant is an independent contractor. ${rules.tax_form} issued where applicable. No employment relationship.

## 2. SERVICES
Per SOW. Professional standard of care.

## 3. COMPENSATION
${rules.currency} per SOW. Net {{PAYMENT_TERMS|30}} days.

## 4. INTELLECTUAL PROPERTY
All deliverables are work-for-hire owned by Client upon full payment. Consultant retains pre-existing tools.

## 5. CONFIDENTIALITY
Consultant holds all Client information in strict confidence. Survives {{CONF_TERM|3 years}}.

## 5.6. ACERBE™
All digital deliverables carry AcerbE™ fingerprint. Tampering voids delivery acceptance and may violate ${acerbe.circumvention} and ${acerbe.tradesecrets}.

## 6. GOVERNING LAW
${rules.governing_law}. Disputes: ${rules.arbitration_body}.

**CLIENT:** Sig: ___ | Name: {{CLIENT_SIGNATORY}} | Date: ___
**CONSULTANT:** Sig: ___ | Name: {{CONSULTANT_SIGNATORY}} | Date: ___`;
}

function buildINV(jur, lang, rules, acerbe) {
  return `## PARTIES
**Company:** {{COMPANY_LEGAL_NAME}} | **Investor:** {{INVESTOR_LEGAL_NAME}}
**Effective Date:** {{EFFECTIVE_DATE}}

---

## 1. INVESTMENT
Investor invests ${rules.currency} {{INVESTMENT_AMOUNT}} in exchange for {{SECURITY_TYPE}} representing {{OWNERSHIP_PERCENTAGE}}% of Company on a fully-diluted basis.

## 2. REPRESENTATIONS — INVESTOR
Investor represents: (a) accredited investor status per ${rules.accredited_investor}; (b) investment for own account; (c) understands restrictions on transfer.

## 3. USE OF PROCEEDS
{{USE_OF_PROCEEDS_DESCRIPTION}}.

## 4. LIQUIDATION PREFERENCE
Investor receives {{LIQUIDATION_MULTIPLE|1x}} liquidation preference before common distribution.

## 5. SECURITIES EXEMPTION
Offered under ${rules.securities_exemption}. No registration required.

## 5.10. ACERBE™
AcerbE™ fingerprints protect all Company digital assets. Investor tampering with AcerbE™ fingerprints on any Company asset: (a) constitutes material breach; (b) triggers forced repurchase at cost; (c) may violate ${acerbe.circumvention} and ${acerbe.tradesecrets}.

## 6. GOVERNING LAW
${rules.governing_law}. Arbitration: ${rules.arbitration_body}.

**COMPANY:** Sig: ___ | Name: {{COMPANY_SIGNATORY}} | Title: {{COMPANY_TITLE}} | Date: ___
**INVESTOR:** Sig: ___ | Name: {{INVESTOR_SIGNATORY}} | Date: ___`;
}

const BODY_BUILDERS = {
  '01-NDA': buildNDA, '02-SLA': buildSLA, '03-MSA': buildMSA,
  '04-ICA': buildICA, '05-EUA': buildEUA, '06-TOS': buildTOS,
  '07-PP':  buildPP,  '08-RPA': buildRPA, '09-LOI': buildLOI,
  '10-MOU': buildMOU, '11-IP':  buildIP,  '12-ESA': buildESA,
  '13-PSA': buildPSA, '14-DPA': buildDPA, '15-WA':  buildWA,
  '16-LIC': buildLIC, '17-PAR': buildPAR, '18-CES': buildCES,
  '19-INV': buildINV,
};

let errors = 0;

for (const jur of jurisdictionsToRun) {
  const rules = JURISDICTION_RULES[jur];
  if (!rules) { console.error(`[ERROR] Unknown jurisdiction: ${jur}`); errors++; continue; }
  const languages = JURISDICTION_LANGUAGES[jur];
  const acerbe = getAcerbeClause(jur);

  for (const doc of DOCS) {
    for (const lang of languages) {
      try {
        const bodyFn = BODY_BUILDERS[doc.id];
        const body = bodyFn(jur, lang, rules, acerbe);
        const content = [
          buildFrontmatter(doc, jur, lang, rules),
          buildHeader(doc, jur, lang, rules),
          body,
          buildFooter(doc, jur, rules, acerbe),
        ].join('\n\n');
        writeTemplate(doc, jur, lang, content);
      } catch (e) {
        console.error(`[ERROR] ${doc.id}/${jur}/${lang}: ${e.message}`);
        errors++;
      }
    }
  }
}

if (errors > 0) {
  console.error(`\n[FAILED] ${errors} error(s) encountered.`);
  process.exit(1);
} else {
  console.log('\n[DONE] All templates generated successfully.');
}
