/**
 * Jurisdiction override rules for LexForge™ template generation
 * Archer Chain Analytics ISC: 102237785
 */

const JURISDICTIONS = ['US', 'CA', 'EU', 'UK', 'AU', 'FR', 'ES'];
const LANGUAGES = ['EN', 'FR', 'ES'];

// Which language(s) are generated per jurisdiction
const JURISDICTION_LANGUAGES = {
  US: ['EN', 'ES'],
  CA: ['EN', 'FR'],
  EU: ['EN', 'FR', 'ES'],
  UK: ['EN'],
  AU: ['EN'],
  FR: ['FR', 'EN'],
  ES: ['ES', 'EN'],
};

const JURISDICTION_RULES = {
  US: {
    currency: 'USD',
    governing_law: 'Delaware',
    arbitration_body: 'American Arbitration Association (AAA)',
    arbitration_rules: 'AAA Commercial Arbitration Rules',
    privacy_law: 'CCPA/CPRA, applicable state privacy laws',
    employment_law: 'applicable federal and state employment law',
    corporate_act: 'Delaware General Corporation Law',
    ip_law: '17 U.S.C. (Copyright Act), 35 U.S.C. (Patent Act), 15 U.S.C. (Lanham Act)',
    breach_notice: '72 hours (GDPR-equivalent) / 30 days (state law)',
    data_transfer: 'within the United States',
    tax_form: 'IRS Form 1099-NEC',
    accredited_investor: 'Rule 501(a) of Regulation D under the Securities Act of 1933',
    securities_exemption: 'Section 4(a)(2) and/or Rule 506(b) of Regulation D',
    footer_law: '17 U.S.C. § 1201; 18 U.S.C. § 1836',
  },
  CA: {
    currency: 'USD',
    governing_law: 'Ontario',
    arbitration_body: 'ADR Institute of Canada (ADRIC)',
    arbitration_rules: 'ADRIC National Arbitration Rules',
    privacy_law: 'Personal Information Protection and Electronic Documents Act (PIPEDA) / Bill C-27 (CPPA)',
    employment_law: 'Canada Labour Code / provincial Employment Standards Act',
    corporate_act: 'Canada Business Corporations Act (CBCA) or applicable provincial Act',
    ip_law: 'Copyright Act (R.S.C. 1985, c. C-42), Patent Act (R.S.C. 1985, c. P-4), Trade-marks Act',
    breach_notice: 'as soon as feasible — PIPEDA breach of security safeguards reporting',
    data_transfer: 'within Canada',
    tax_form: 'T4A (Statement of Pension, Retirement, Annuity, and Other Income)',
    accredited_investor: 'NI 45-106 (National Instrument 45-106 Prospectus Exemptions)',
    securities_exemption: 'accredited investor exemption under NI 45-106 s. 2.3',
    footer_law: 'Copyright Act (Canada) s. 41.1; common law trade secrets',
  },
  EU: {
    currency: 'USD',
    governing_law: 'Ireland (EU Member State)',
    arbitration_body: 'ICC International Court of Arbitration',
    arbitration_rules: 'ICC Arbitration Rules',
    privacy_law: 'General Data Protection Regulation (EU) 2016/679 (GDPR)',
    employment_law: 'applicable EU Directives and Member State employment law',
    corporate_act: 'applicable Member State company law',
    ip_law: 'Directive 2001/29/EC (InfoSoc), Directive (EU) 2016/943 (Trade Secrets)',
    breach_notice: '72 hours (GDPR Art. 33)',
    data_transfer: 'within the EEA or under adequate safeguards (SCCs)',
    tax_form: 'applicable VAT invoice requirements',
    accredited_investor: 'MiFID II / Prospectus Regulation (EU) 2017/1129',
    securities_exemption: 'Prospectus Regulation exemptions (Art. 1(4))',
    footer_law: 'Directive 2001/29/EC Art. 6; Directive (EU) 2016/943',
  },
  UK: {
    currency: 'USD',
    governing_law: 'England and Wales',
    arbitration_body: 'London Court of International Arbitration (LCIA)',
    arbitration_rules: 'LCIA Arbitration Rules',
    privacy_law: 'UK GDPR / Data Protection Act 2018',
    employment_law: 'Employment Rights Act 1996 / applicable UK employment law',
    corporate_act: 'Companies Act 2006',
    ip_law: 'Copyright, Designs and Patents Act 1988; Trade Marks Act 1994; Patents Act 1977',
    breach_notice: '72 hours (UK GDPR Art. 33)',
    data_transfer: 'within the UK or under UK adequacy regulations',
    tax_form: 'HMRC Self Assessment / IR35 considerations',
    accredited_investor: 'FCA Conduct of Business Sourcebook (COBS) / Financial Promotion Order',
    securities_exemption: 'Financial Services and Markets Act 2000 (Financial Promotion) Order 2005',
    footer_law: 'CDPA 1988 s. 296ZA; Trade Secrets (Enforcement, etc.) Regulations 2018',
  },
  AU: {
    currency: 'USD',
    governing_law: 'New South Wales',
    arbitration_body: 'Australian Centre for International Commercial Arbitration (ACICA)',
    arbitration_rules: 'ACICA Arbitration Rules',
    privacy_law: 'Privacy Act 1988 (Cth) / Australian Privacy Principles (APPs)',
    employment_law: 'Fair Work Act 2009 (Cth) / applicable state employment law',
    corporate_act: 'Corporations Act 2001 (Cth)',
    ip_law: 'Copyright Act 1968 (Cth); Patents Act 1990 (Cth); Trade Marks Act 1995 (Cth)',
    breach_notice: '30 days (Notifiable Data Breaches scheme — Privacy Act s. 26WK)',
    data_transfer: 'within Australia or under APPs cross-border disclosure rules',
    tax_form: 'ATO Tax Invoice / ABN requirements',
    accredited_investor: 'Corporations Act 2001 s. 708 (sophisticated investor)',
    securities_exemption: 'Corporations Act 2001 s. 708 personal offer exemptions',
    footer_law: 'Copyright Act 1968 (Cth) s. 116AN; common law (breach of confidence)',
  },
  FR: {
    currency: 'USD',
    governing_law: 'France (Paris)',
    arbitration_body: 'Chambre de Commerce Internationale (CCI)',
    arbitration_rules: 'Règlement d\'arbitrage de la CCI',
    privacy_law: 'RGPD (UE) 2016/679 / Loi n° 78-17 (Informatique et Libertés)',
    employment_law: 'Code du travail français',
    corporate_act: 'Code de commerce français',
    ip_law: 'Code de la propriété intellectuelle (CPI)',
    breach_notice: '72 heures (RGPD Art. 33)',
    data_transfer: 'au sein de l\'EEE ou sous garanties appropriées (CCT)',
    tax_form: 'Facture TVA conforme au CGI',
    accredited_investor: 'AMF / Règlement (UE) Prospectus 2017/1129',
    securities_exemption: 'exemptions du Règlement Prospectus (Art. 1(4))',
    footer_law: 'CPI Art. L. 331-5; directive (UE) 2016/943 transposée',
  },
  ES: {
    currency: 'USD',
    governing_law: 'España (Madrid)',
    arbitration_body: 'Corte de Arbitraje de la Cámara de Comercio de Madrid',
    arbitration_rules: 'Reglamento de Arbitraje de la Cámara de Comercio de Madrid',
    privacy_law: 'RGPD (UE) 2016/679 / LOPDGDD (LO 3/2018)',
    employment_law: 'Estatuto de los Trabajadores (ET) / legislación laboral aplicable',
    corporate_act: 'Ley de Sociedades de Capital (LSC)',
    ip_law: 'Real Decreto Legislativo 1/1996 (LPI); Ley 24/2015 de Patentes',
    breach_notice: '72 horas (RGPD Art. 33)',
    data_transfer: 'dentro del EEE o bajo garantías adecuadas (CCT)',
    tax_form: 'Factura según requisitos AEAT / IVA',
    accredited_investor: 'CNMV / Reglamento (UE) Prospecto 2017/1129',
    securities_exemption: 'exenciones del Reglamento Prospecto (Art. 1(4))',
    footer_law: 'LPI Art. 160; Ley 1/2019 de Secretos Empresariales',
  },
};

const LANGUAGE_LABELS = {
  EN: { lang: 'English', locale: 'en' },
  FR: { lang: 'French', locale: 'fr' },
  ES: { lang: 'Spanish', locale: 'es' },
};

module.exports = {
  JURISDICTIONS,
  LANGUAGES,
  JURISDICTION_LANGUAGES,
  JURISDICTION_RULES,
  LANGUAGE_LABELS,
};
