'use strict';

const ALL_JURISDICTIONS = ['US', 'CA', 'EU', 'UK', 'BR', 'AE', 'SG'];
const ALL_LANGUAGES = ['EN', 'FR', 'DE', 'PT', 'ES', 'AR', 'ZH'];

const JURISDICTION_LANGUAGES = {
  US: ALL_LANGUAGES,
  CA: ALL_LANGUAGES,
  EU: ALL_LANGUAGES,
  UK: ALL_LANGUAGES,
  BR: ALL_LANGUAGES,
  AE: ALL_LANGUAGES,
  SG: ALL_LANGUAGES,
};

const JURISDICTION_RULES = {
  US: {
    currency: 'USD',
    governing_law: 'Delaware, United States',
    arbitration_body: 'American Arbitration Association (AAA)',
    arbitration_rules: 'AAA Commercial Arbitration Rules',
    privacy_law: 'CCPA/CPRA (California) and applicable U.S. state privacy laws',
    ip_law: '17 U.S.C. (Copyright Act) / 35 U.S.C. (Patent Act)',
    breach_notice: '72 hours (California) / 30 days (federal standard)',
    data_transfer: 'within the United States',
    tax_form: '1099-NEC',
    accredited_investor: 'SEC Rule 501 of Regulation D',
    securities_exemption: 'Regulation D, Rule 506(b)',
    footer_law: '17 U.S.C. § 1201 (DMCA) / 18 U.S.C. § 1836 (DTSA)',
  },
  CA: {
    currency: 'USD',
    governing_law: 'Ontario, Canada',
    arbitration_body: 'ADR Institute of Canada (ADRIC)',
    arbitration_rules: 'ADRIC Arbitration Rules',
    privacy_law: 'PIPEDA / Bill C-27 (CPPA)',
    ip_law: 'Copyright Act (R.S.C. 1985, c. C-42)',
    breach_notice: '72 hours',
    data_transfer: 'within Canada or as permitted under PIPEDA',
    tax_form: 'T4A',
    accredited_investor: 'National Instrument 45-106',
    securities_exemption: 'NI 45-106 Accredited Investor Exemption',
    footer_law: 'Copyright Act s. 41.1 / Uniform Trade Secrets Act (provincial)',
  },
  EU: {
    currency: 'USD',
    governing_law: 'Republic of Ireland (EU member state)',
    arbitration_body: 'Court of Arbitration of the International Chamber of Commerce (ICC)',
    arbitration_rules: 'ICC Arbitration Rules',
    privacy_law: 'GDPR (EU) 2016/679',
    ip_law: 'Directive 2001/29/EC (InfoSoc) / Directive (EU) 2016/943 (Trade Secrets)',
    breach_notice: '72 hours (GDPR Art. 33)',
    data_transfer: 'within the EEA or under approved transfer mechanisms (SCCs)',
    tax_form: 'VAT invoice (where applicable)',
    accredited_investor: 'MiFID II qualified investor definition',
    securities_exemption: 'Prospectus Regulation (EU) 2017/1129 exemption',
    footer_law: 'Directive 2001/29/EC Art. 6 / Directive (EU) 2016/943',
  },
  UK: {
    currency: 'USD',
    governing_law: 'England and Wales',
    arbitration_body: 'London Court of International Arbitration (LCIA)',
    arbitration_rules: 'LCIA Arbitration Rules',
    privacy_law: 'UK GDPR / Data Protection Act 2018',
    ip_law: 'Copyright, Designs and Patents Act 1988',
    breach_notice: '72 hours (UK GDPR Art. 33)',
    data_transfer: 'within the UK or under UK adequacy regulations',
    tax_form: 'Self-assessment / VAT invoice',
    accredited_investor: 'FCA High Net Worth Individual / Sophisticated Investor',
    securities_exemption: 'Financial Services and Markets Act 2000 (Financial Promotion) Order 2005',
    footer_law: 'CDPA 1988 s. 296ZA / Trade Secrets (Enforcement, etc.) Regulations 2018',
  },
  BR: {
    currency: 'USD',
    governing_law: 'São Paulo, Brazil',
    arbitration_body: 'Brazil-Canada Chamber of Commerce (CCBC)',
    arbitration_rules: 'CCBC Arbitration Rules',
    privacy_law: 'Lei Geral de Proteção de Dados (LGPD) — Lei nº 13.709/2018',
    ip_law: 'Lei nº 9.610/1998 (Lei de Direitos Autorais) / Lei nº 9.279/1996 (Propriedade Industrial)',
    breach_notice: '72 hours (LGPD Art. 48)',
    data_transfer: 'within Brazil or to countries with adequate protection per ANPD',
    tax_form: 'NF-e / RPA (Recibo de Pagamento a Autônomo)',
    accredited_investor: 'CVM Resolution 30 (Investor Qualification)',
    securities_exemption: 'CVM Instruction 588 (Equity Crowdfunding) / CVM Resolution 160',
    footer_law: 'Lei nº 9.610/1998 Art. 107 / Lei nº 9.279/1996',
  },
  AE: {
    currency: 'USD',
    governing_law: 'Dubai International Financial Centre (DIFC), UAE',
    arbitration_body: 'Dubai International Arbitration Centre (DIAC)',
    arbitration_rules: 'DIAC Arbitration Rules 2022',
    privacy_law: 'DIFC Data Protection Law (DIFC Law No. 5 of 2020) / UAE Federal DPL',
    ip_law: 'UAE Federal Law No. 38 of 2021 (Copyright) / UAE Federal Law No. 37 of 2022 (Trademarks)',
    breach_notice: '72 hours (DIFC DPL)',
    data_transfer: 'within the UAE or DIFC-approved jurisdictions',
    tax_form: 'VAT invoice (UAE VAT Law Federal Decree No. 8 of 2017)',
    accredited_investor: 'DFSA Qualified Investor definition',
    securities_exemption: 'DFSA Markets Law exemption / SCA Board Decision No. 3 of 2017',
    footer_law: 'UAE Federal Law No. 38 of 2021 Art. 38 / DIFC Law No. 5 of 2020',
  },
  SG: {
    currency: 'USD',
    governing_law: 'Singapore',
    arbitration_body: 'Singapore International Arbitration Centre (SIAC)',
    arbitration_rules: 'SIAC Arbitration Rules',
    privacy_law: 'Personal Data Protection Act 2012 (PDPA)',
    ip_law: 'Copyright Act 2021 (Singapore) / Trade Secrets (common law)',
    breach_notice: '3 business days (PDPA mandatory breach notification)',
    data_transfer: 'within Singapore or under PDPA transfer obligations',
    tax_form: 'Invoice (GST registration where applicable)',
    accredited_investor: 'Securities and Futures Act (Cap. 289) — Accredited Investor definition',
    securities_exemption: 'SFA s. 272B (Small Offers) / s. 275 (Private Placement)',
    footer_law: 'Copyright Act 2021 s. 261 / PDPA / common law breach of confidence',
  },
};

module.exports = { JURISDICTION_RULES, JURISDICTION_LANGUAGES, ALL_JURISDICTIONS, ALL_LANGUAGES };
